tasks:
  - name: Start Logto
    init: |
      curl -fsSL https://raw.githubusercontent.com/logto-io/logto/v1.10.1/docker-compose.yml > docker-compose.yml
      docker compose pull
    command: |
      DEV_FEATURES_ENABLED=1 ENDPOINT=$(gp url 3001) ADMIN_ENDPOINT=$(gp url 3002) docker compose -p logto up

ports:
  - name: Logto
    description: The Logto core service
    port: 3001
    visibility: public
  - name: Admin Console
    description: The Admin Console for Logto core service
    port: 3002
    visibility: public
